
version: '3.9'
services:

#  p74_1:
#    build:
#      context: .
#      dockerfile: ./p74_1/Dockerfile
#    container_name: p74_1
#    working_dir: /var/www/html
#    ports:
#      - "80:80"
#    volumes:
#      - ./p74_1/www:/var/www/html
#      - ./nginx.conf:/etc/nginx/nginx.conf
#      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
#    restart: always
#    command: sh -c "composer install && supervisord -c /etc/supervisor/conf.d/supervisord.conf"

  p73:
    build:
      context: .
      dockerfile: ./p73/Dockerfile
    container_name: p73
    working_dir: /var/www/html
    ports:
      - "8080:80"
    volumes:
      - ./p73/www:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    restart: always
    command: sh -c "supervisord -c /etc/supervisor/conf.d/supervisord.conf"

  p74:
    build:
      context: .
      dockerfile: ./p74/Dockerfile
    container_name: p74
    working_dir: /var/www/html
    command: sh -c "composer install && supervisord -c /etc/supervisor/conf.d/supervisord.conf"
    ports:
      - "80:80"
    volumes:
      - ./p74/www:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./supervisord.conf:/etc/supervisor/conf.d/supervisord.conf
    restart: always




#  libreoffice:
#    build:
#      context: ./libre
#      dockerfile: Dockerfile
#    container_name: libreoffice
#    ports:
#      - "80:80"
#    restart: always

#  office:
#    image: onlyoffice/documentserver:latest
#    ports:
#      - 80:80
#      - 443:443
#    restart: always
