
version: '3.9'
services:

  p73:
    build:
      context: .
      dockerfile: ./p73/Dockerfile
    container_name: p73
    working_dir: /var/www/html
    ports:
      - "8080:80"
    volumes:
      - ./p73/www:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always

  p74:
    build:
      context: .
      dockerfile: ./p74/Dockerfile
    container_name: p74
    working_dir: /var/www/html
    command: >
      sh -c "composer install"
    ports:
      - "80"
    volumes:
      - ./p74/www:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart: always




#  libreoffice:
#    build:
#      context: ./libre
#      dockerfile: Dockerfile
#    container_name: libreoffice
#    ports:
#      - "80:80"
#    restart: always

#  office:
#    image: onlyoffice/documentserver:latest
#    ports:
#      - 80:80
#      - 443:443
#    restart: always
